### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by jeansaigne** [OtaK/dailymotion-sdk-node#2]
Bonjour Mathieu,
j'aimerai utiliser ton package node plutot que de packager moi-même le sdk dailymotion qui est déjà très simple en soit. Cependant je ne comprends presque rien à ton README...
J'ai déjà réussi à installer le package via npm et même ça ce n'est pas indiqué.
#### Ou est le quickstart ? Quel objet instancier ?

Voici un extrait d'un exemple de Readme pour l'homologue de ton package via soundcloud:

<code>
// Initialize client</code>
<code>npm install --save node-soundcloud;</code>
<code>var SC = require('node-soundcloud');</code>
<code>SC.init({
  id: 'your SoundCloud client ID',
  secret: 'your SoundCloud client secret',
  uri: 'your SoundCloud redirect URI'
});</code>

La je ne me pose aucune quesiton, il n'y a pas de magie; tandis que tes setCredential, setScope, ou autre api, se sont des fonctions? des méthodes d'objet ? quel objet ?

Bref un exemple d'utilisation peut parfois être bien plus parlant qu'une tentative d'explication exhaustive qui ne comporte pas la base.

Merci par avance pour l'effort si celui-ci se fait.
Cordialement.

**Comment by OtaK** [comment]
Hello Aymeric,

Pas de souci, le readme de mon sdk est autogénéré en fonction des docblocks du code.
Je vais ajouter un dossier examples avec 2-3 exemples comme lister les vidéos d'une playlist, uploader une vidéo, etc.

Pour la petite histoire, dans les besoins initiaux de ce SDK, j'avais besoin d'agir en tant que *plusieurs* comptes, d'où le fait d'avoir besoin d'instancier un nouveau client à chaque compte différent (afin de pouvoir faire de l'upload parallèle de vidéos sur X comptes différents sans avoir de race conditions si jamais l'initialisation avec les credentials était centralisée comme avec le client soundcloud).

Bref, je tiendrai à jour l'issue lorsque j'aurai ajouté les exemples, merci de la requête ! :)

**Comment by atrhacker** [comment]
Salut

Je suis également, hyper interessé par les exemples sur l'instance de la lib.
On comprends l'idée en allant voir le code source, mais c'est vrai que deux trois exemples permettrait d'aller plus vite.

Merci en tout cas d'avoir porter le sdk en packages, ca fait deja gagner du temps..

Bonne journée

Anselme

**Comment by OtaK** [comment]
Hello,

Je viens d'ajouter un fichier exemples. N'hésitez pas à me faire des retours sur ce dernier.

Encore désolé du délai.

Bonne journée à tous,
Merci,
Mathieu.

**Comment by jeansaigne** [comment]
Merci beaucoup Otak pour ton implication; j'essaie cela dès que possible.
